### ISSUE TITLE
It is now no longer possible to run the back-end locally without environment variables:

### ISSUE THREAD

**Issue by MartinDeLaTorre** [revature-rss-ben-1370/e-commerce-backend#8]
# It is now no longer possible to run the back-end locally without environment variables:

As seen in the application.yml:
```
${DB_PLATFORM}
${DB_URL}
${DB_DRIVER}
```

These variables are set 2 different ways, 
A) for the local docker container build, and 
B) for the k8s cluster.

For the local build, the Dockerfile sets the variables:
```
ARG DB_PLATFORM=org.hibernate.dialect.H2Dialect
ARG DB_URL=jdbc:h2:mem:test;MODE=PostgreSQL
ARG DB_DRIVER=org.h2.Driver
```

For the k8s cluster, the back-end-deployment.yaml 
```
          env:
            - name: DB_PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: DB_URL
              value: jdbc:postgresql://db-service.p3-space.svc.cluster.local:5432/postgres?user=postgres&password=example
            - name: DB_DRIVER
              value: org.postgresql.Driverets the variables:
```

----
### Why did we do this?
Honestly, we didn't want to, when maven builds the images, it _insists_ on running the test cases (which is a good thing btw) but we are building images locally on our machine, so maven is unable to access the postgress pod, and pretty much all the test cases fail.

But we also didn't want to get rid of the postgress pod because we (as SREs) insist on a persistent volume for the data.

So to get the best of both worlds (testing capability and persistent volume on the cluster), the application.yml uses environment variables, and maven uses an in memory database for testing, and the k8s cluster uses the postgres pod for the deployment.

_Originally posted by @MartinDeLaTorre in https://github.com/revature-rss-ben-1370/e-commerce-backend/pull/7#pullrequestreview-1032208260_
